version: '3.8'
services:
  app:
    container_name: nodejs-chat-server
    build: .
    ports:
      - "${PORT}:${PORT}"
      - "${WS_PORT}:${WS_PORT}"
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  redis:
    container_name: redis
    image: redis
    networks:
      - app-network

  nginx-proxy:
    container_name: proxy
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
