name: Deploy on Dev

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_on_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Generate and Upload .env File
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} "
            if [ ! -d NodeJS-Chat-Server ]; then
              echo 'NodeJS-Chat-Server directory does not exist. Cloning...'
              git clone https://github.com/gevorgabgaryan/NodeJS-Chat-Server.git NodeJS-Chat-Server
            fi
            echo 'Creating .env file...'
            cd NodeJS-Chat-Server &&
            touch .env &&
            echo PORT=${{ secrets.PORT }} >> .env &&
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env &&
            echo JWT_EXPIRE_IN=${{ secrets.JWT_EXPIRE_IN }} >> .env &&
            echo MONGO_DB_URL=${{ secrets.MONGO_DB_URL }} >> .env &&
            echo MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} >> .env &&
            echo WS_PORT=${{ secrets.WS_PORT }} >> .env &&
            echo REDIS_URL=${{ secrets.REDIS_URL }} >> .env &&
            echo NODE_ENV=production >> .env
            echo '.env file created and populated.'
          "

      - name: Pull latest changes and restart application
        run: |
          ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} "
            if [ -d NodeJS-Chat-Server ] && [ -d NodeJS-Chat-Server/.git ]; then
              echo 'Deploying application...'
              cd NodeJS-Chat-Server &&
              git pull &&
              docker-compose up --build -d
              echo 'Deployment complete.'
            else
              echo 'NodeJS-Chat-Server is not a valid Git repository. Cloning...'
              git clone https://github.com/gevorgabgaryan/NodeJS-Chat-Server.git NodeJS-Chat-Server
              cd NodeJS-Chat-Server &&
              docker-compose up --build -d
              echo 'Deployment complete.'
            fi
          "

